ecs_cluster_name = "tarmizi-ecs-cluster-prod"
ecs_service_name = "tarmizi-ecs-service-prod"
ecs_task_defn_family = "tarmizi-ecs-task-def-prod"
ecs_container_name = "tarmizi-container-prod"
ecs_port_name = "tarmizi-3000-tcp-prod"